### ISSUE TITLE
Missing python2 module 'urlparse'

### ISSUE THREAD

**Issue by joaocandre** [ros-melodic-arch/ros-melodic-gazebo-ros#3]
I'm not sure if this is he right place to post this, but I am getting a python error when launching gazebo from a launch file:

`
    Traceback (most recent call last):
      File "/opt/ros/melodic/lib/gazebo_ros/spawn_model", line 25, in <module>
        from urlparse import urlsplit, SplitResult
    ModuleNotFoundError: No module named 'urlparse'
`

Which obviously happens because `urlparse` is a python2 module which was renamed to `urllib.parse` in python3. Since ROS and Gazebo on arch are supposed to run on top of python3, is there a workaround this that does not involve explicitly calling python2? Because that would require several python2 versions of ROS packages that conflict with the ones on the `ros-melodic-desktop-full` package

**Comment by acxz** [comment]
Maybe take a look at the following [comment](https://aur.archlinux.org/packages/gazebo/#comment-699042) on the gazebo aur page? It seems astier ran into this problem and presumably fixed it, however, those changes are not part of the gazebo-ros aur PKGBUILD, yet.

**Comment by bionade24** [comment]
Issue gets fixed soon when I update the package source.

**Comment by bionade24** [comment]
@joaocandre This isn't the right place, this isn't the gazebo package.

**Comment by acxz** [comment]
@bionade24 I am not entirely convinced that this issue is gazebo's fault. I haven't had time to recreate this issue, but I did create #4 to update the package to the newest version. Maybe that fixes it? If not then it could very well end up being an upstream issue. Again not sure, but @joaocandre if you could try to recreate the issue once the new version is available on the AUR that would be helpful.

EDIT: yeah from what i can tell the new update doesn't fix the issue. I thinking posting an upstream issue to the `gazebo-ros-pkgs` repo would be the best things moving forward.

**Comment by acxz** [comment]
Reopening this as issue since it is caused by this package.
